### ISSUE TITLE
kind plea from visually impaired user

### ISSUE THREAD

**Issue by JanuszChmiel** [akbarri/ExaGear-SoundFix#2]
Dear MR akbarri,
I have found your sound fix pack. I Am aware, that it have been primarily created for Exagear product. But I have one programmers plea to you as a elite C language programmer of this native .so library.
Is it possible to call libasound_module_pcm_android.so directly from installed Linux distribution, which run thanks to Proot and The distribution is being executed from Termux? I Am running latest stable Ubuntu 22.04 LTS (Jammy Jellyfish) AArch64. ANd I Am using Android 8.0 Oreo.
Or libasound_module_pcm_android.so can be only used from Android app which will call it? I want to improve The time delay of Espeak-ng and Speech-dispatcher. Termux support reliable Pulseaudio sound server which uses Open Sless protocol to send audio sound data to some Android sound service. But I Am dreaming, if Espeak-ng could react more faster if user would have The chance to use some .so library which would allow him to directly use ALSA sound server.
even on The non rooted devices.
It is fact, that Exagear demonstration version has worked very fast when I have tried some audio games for visually impaired users.
Thank you veryv very much for your time and for your answer.

**Comment by akbarri** [comment]
libasound_module_pcm_android.so can be only used from Android app that using ALSA-lib as backend.
Issues with Termux is integrating ALSA-lib / ALSA-plugins, details here https://github.com/termux/termux-packages/issues/821
